Repository swyp-season8-4-team/frontend_mobile, pull requests merged in 2025-04, with the labels that each got.

#24 [FEATURE] Dialog 수정
  ios/Podfile.lock
  lib/common/design_system/component/badge/new_badge.dart
  lib/common/design_system/component/dialog/dialog.dart
  lib/common/design_system/component/progress_indicator/linear_progress_indicator.dart
  lib/common/design_system/component/search/search.dart
  lib/common/design_system/component/snackbar/snack_bar_right_item.dart
  lib/common/design_system/component/textfield/input_box.dart
  lib/common/design_system/component/textfield/text_field.dart
Labels: enhancement

#27 [FEATURE] Button 생성
  lib/common/design_system/component/button/dessert_mate_button.dart
  lib/common/design_system/component/button/fill_button.dart
  lib/common/design_system/component/button/icon_button.dart
  lib/common/design_system/component/button/outline_button.dart
  lib/common/design_system/component/button/pill_button.dart
  lib/common/design_system/component/button/pill_outline_button.dart
  lib/common/design_system/component/button/text_button.dart
Labels: enhancement

#21 [FEATURE] Expandable Text, ButtonInputBox 추가
  lib/common/design_system/component/etc/expandable_text.dart
  lib/common/design_system/component/textfield/button_input_box.dart
  lib/common/design_system/component/textfield/input_box.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#25 [FEATURE] Tab 구현
  lib/common/design_system/component/tab/tab.dart
Labels: enhancement

#30 [FEATURE] Bottom Sheet
  ios/Podfile.lock
  lib/common/design_system/component/bottom_sheet/bottom_sheet.dart
  lib/common/design_system/component/button/outline_button.dart
  lib/common/design_system/foundation/color/scale_color_config.dart
Labels: enhancement

#32 [FEATURE] Icongraphy 변경에 따른 아이콘 추가
  asset/icon/dessert/birthday_2_line.svg
  asset/icon/dessert/bread_line.svg
  asset/icon/dessert/cake_line.svg
  asset/icon/dessert/cupcake_line.svg
  asset/icon/dessert/donut_line.svg
  asset/icon/editor/bookmark_line.svg
  asset/icon/menu/more_1_fill.svg
  asset/icon/menu/more_2_fill.svg
  asset/icon/system/keyboard-down_1_line.svg
  asset/icon/system/minus_1_line.svg
  asset/icon/user/group_1_line.svg
  asset/icon/user/user_1_line.svg
  asset/icon/user/user_2_line.svg
  asset/icon/user/user_3_line.svg
  lib/common/gen_asset/assets.gen.dart
  pubspec.yaml
Labels: enhancement

#29 [FEATURE] 저장된 가게 관련 API 연동 추가
  lib/data/data_source/remote/generated/user_store_remote_data_source.g.dart
  lib/data/data_source/remote/user_store_remote_data_source.dart
  lib/data/entity/user_store/generated/get_user_store_list_entity.g.dart
  lib/data/entity/user_store/generated/user_store_list_entity.g.dart
  lib/data/entity/user_store/generated/user_store_list_summary_entity.g.dart
  lib/data/entity/user_store/generated/user_store_location_entity.g.dart
  lib/data/entity/user_store/user_store_list_entity.dart
  lib/data/entity/user_store/user_store_list_summary_entity.dart
  lib/data/entity/user_store/user_store_location_entity.dart
  lib/data/query_param/user_store/add_user_store_list_query_param.dart
  lib/data/query_param/user_store/generated/add_user_store_list_query_param.g.dart
  lib/data/query_param/user_store/generated/update_user_store_list_query_param.g.dart
  lib/data/query_param/user_store/update_user_store_list_query_param.dart
Labels: enhancement

#31 [FEATURE] CustomDialog의 button area 수정
  lib/common/design_system/component/dialog/dialog.dart
Labels: enhancement

#34 [FEATURE] 라우팅을 위한 go_router 기반 라우터 설정
  lib/core/resource/route_info.dart
  lib/main.dart
  lib/presentation/local_login/local_login_view.dart
  lib/presentation/router/router.dart
  lib/presentation/router/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#38 [FEATURE] Naver Map SDK 연동 추가
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/gradle.properties
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/common/env/env.dart
  lib/core/manager/geolocation/geo_location_exception.dart
  lib/core/manager/geolocation/geo_location_manager.dart
  lib/core/manager/geolocation/geo_location_service_impl.dart
  lib/main.dart
  lib/presentation/map/map_view.dart
  lib/presentation/router/router.dart
  lib/presentation/router/routes.dart
  lib/presentation/widget/scaffold_with_navigation_bar.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#28 [FEATURE] 검색, 가게 관련 API 연동 추가
  lib/data/data_source/remote/generated/search_remote_data_source.g.dart
  lib/data/data_source/remote/generated/store_remote_data_source.g.dart
  lib/data/data_source/remote/search_remote_data_source.dart
  lib/data/data_source/remote/store_remote_data_source.dart
  lib/data/entity/search/generated/search_popular_entity.g.dart
  lib/data/entity/search/generated/search_recent_entity.g.dart
  lib/data/entity/search/search_popular_entity.dart
  lib/data/entity/search/search_recent_entity.dart
  lib/data/entity/store/generated/store_by_location_entity.g.dart
  lib/data/entity/store/generated/store_detail_entity.g.dart
  lib/data/entity/store/generated/store_holiday_entity.g.dart
  lib/data/entity/store/generated/store_operating_hour_entity.g.dart
  lib/data/entity/store/generated/store_summary_entity.g.dart
  lib/data/entity/store/store_by_location_entity.dart
  lib/data/entity/store/store_detail_entity.dart
  lib/data/entity/store/store_holiday_entity.dart
  lib/data/entity/store/store_operating_hour_entity.dart
  lib/data/entity/store/store_summary_entity.dart
  lib/data/query_param/search/generated/get_search_popular_query_param.g.dart
  lib/data/query_param/search/get_search_popular_query_param.dart
  lib/data/query_param/store/generated/get_my_preferences_stores_by_location_query_param.g.dart
  lib/data/query_param/store/generated/get_stores_by_location_query_param.g.dart
  lib/data/query_param/store/get_my_preferences_stores_by_location_query_param.dart
  lib/data/query_param/store/get_stores_by_location_query_param.dart
Labels: enhancement

#39 [FEATURE] 지도 내 모든 선호도 표시 구현
  asset/image/1.5x/bee.png
  asset/image/1.5x/coupon_bedge.png
  asset/image/1.5x/current_location.png
  asset/image/1.5x/logo.png
  asset/image/1.5x/marker_1.png
  asset/image/2.0x/bee.png
  asset/image/2.0x/coupon_bedge.png
  asset/image/2.0x/current_location.png
  asset/image/2.0x/logo.png
  asset/image/2.0x/marker_1.png
  asset/image/3.0x/bee.png
  asset/image/3.0x/coupon_bedge.png
  asset/image/3.0x/current_location.png
  asset/image/3.0x/logo.png
  asset/image/3.0x/marker_1.png
  asset/image/4.0x/bee.png
  asset/image/4.0x/coupon_bedge.png
  asset/image/4.0x/current_location.png
  asset/image/4.0x/logo.png
  asset/image/4.0x/marker_1.png
  asset/image/bee.png
  asset/image/coupon_bedge.png
  asset/image/current_location.png
  asset/image/marker_1.png
  ios/Podfile.lock
  lib/common/design_system/component/button/dessert_mate_button.dart
  lib/common/design_system/component/chip/floating_chip.dart
  lib/common/design_system/component/etc/marker/coupon_include_marker.dart
  lib/common/design_system/component/etc/marker/default_marker.dart
  lib/common/gen_asset/assets.gen.dart
  lib/core/resource/params/no_params.dart
  lib/core/resource/status.dart
  lib/data/data_source/remote/generated/preference_remote_data_source.g.dart
  lib/data/data_source/remote/preference_remote_data_source.dart
  lib/data/entity/preference/generated/preference_entity.g.dart
  lib/data/entity/preference/preference_entity.dart
  lib/data/mapper/preference_mapper.dart
  lib/data/repository_impl/preference_repository_impl.dart
  lib/domain/model/preference/preference_model.dart
  lib/domain/repository/preference_repository.dart
  lib/domain/usecase/preference/get_all_preferences_usecase.dart
  lib/main.dart
  lib/presentation/map/generated/map_view_model.freezed.dart
  lib/presentation/map/map_state.dart
  lib/presentation/map/map_view.dart
  lib/presentation/map/map_view_model.dart
  lib/presentation/widget/scaffold_with_navigation_bar.dart
Labels: enhancement

#35 [FEATURE] 비밀번호 찾기
  ios/Podfile.lock
  lib/common/design_system/component/bottom_sheet/bottom_sheet.dart
  lib/common/design_system/component/button/fill_button.dart
  lib/common/design_system/component/button/outline_button.dart
  lib/common/design_system/component/button/pill_outline_button.dart
  lib/common/design_system/component/textfield/input_box.dart
  lib/common/design_system/component/top_bar/sub_top_bar.dart
  lib/core/resource/email.dart
  lib/core/util/find_password_wrapper.dart
  lib/core/util/loading/global_loading_overlay.dart
  lib/core/util/loading/loading_overlay.dart
  lib/data/data_source/remote/email_remote_data_source.dart
  lib/data/data_source/remote/generated/email_remote_data_source.g.dart
  lib/data/entity/auth/local_login_entity.dart
  lib/data/entity/email/email_verification_request_entity.dart
  lib/data/entity/email/email_verify_entity.dart
  lib/data/entity/email/generated/email_verification_request_entity.g.dart
  lib/data/entity/email/generated/email_verify_entity.g.dart
  lib/data/mapper/email_mapper.dart
  lib/data/repository_impl/email_repository_impl.dart
  lib/data/request_body/email/email_verification_request_request_body.dart
  lib/data/request_body/email/email_verify_request_body.dart
  lib/data/request_body/email/generated/email_verification_request_request_body.g.dart
  lib/data/request_body/email/generated/email_verify_request_body.g.dart
  lib/domain/model/email/email_verification_request_model.dart
  lib/domain/model/email/email_verify_model.dart
  lib/domain/param/email/email_verification_request_params.dart
  lib/domain/param/email/email_verify_params.dart
  lib/domain/repository/email_repository.dart
  lib/domain/usecase/email/post_email_verification_request_usecase.dart
  lib/domain/usecase/email/post_email_verify_usecase.dart
  lib/presentation/find_password/find_password_state.dart
  lib/presentation/find_password/find_password_view_model.dart
  lib/presentation/find_password/generated/find_password_view_model.freezed.dart
  lib/presentation/find_password/view/find_password_step1.dart
  lib/presentation/find_password/view/find_password_step2.dart
  lib/presentation/find_password/view/find_password_step3.dart
  lib/presentation/local_login/generated/local_login_view_model.freezed.dart
  lib/presentation/local_login/local_login_view.dart
  lib/presentation/router/router.dart
  lib/presentation/router/routes.dart
Labels: enhancement

#40 [FEATURE] Hexagon Grid 추가
  asset/icon/etc/hexagon.svg
  lib/common/design_system/component/hexagon_grid/hexagon_grid.dart
  lib/common/gen_asset/assets.gen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#42 [FEATURE] 지도를 통해 반경 내 가게 조회 및 간략 정보 조회 기능 구현
  asset/icon/map/14x14_address_line.svg
  asset/image/1.5x/marker_selected.png
  asset/image/2.0x/marker_selected.png
  asset/image/3.0x/marker_selected.png
  asset/image/4.0x/marker_selected.png
  asset/image/marker_selected.png
  ios/Podfile.lock
  lib/common/design_system/component/bottom_sheet/bottom_sheet.dart
  lib/common/design_system/component/etc/map/map_icon_button.dart
  lib/common/design_system/component/etc/map/store_info_bottom_sheet_content.dart
  lib/common/design_system/component/hexagon_grid/hexagon_grid.dart
  lib/common/gen_asset/assets.gen.dart
  lib/core/resource/constant.dart
  lib/core/util/naver_map_util.dart
  lib/data/data_source/mock/store_mock_data_source.dart
  lib/data/data_source/remote/store_remote_data_source.dart
  lib/data/entity/store/generated/store_detail_entity.g.dart
  lib/data/entity/store/generated/store_summary_entity.g.dart
  lib/data/entity/store/generated/store_top_preference_entity.g.dart
  lib/data/entity/store/store_detail_entity.dart
  lib/data/entity/store/store_summary_entity.dart
  lib/data/entity/store/store_top_preference_entity.dart
  lib/data/mapper/store_mapper.dart
  lib/data/repository_impl/store_repository_impl.dart
  lib/domain/model/store/store_by_location_model.dart
  lib/domain/model/store/store_holiday_model.dart
  lib/domain/model/store/store_operating_hour_model.dart
  lib/domain/model/store/store_summary_model.dart
  lib/domain/model/store/store_top_preference_model.dart
  lib/domain/param/store/get_my_preferences_stores_by_location_params.dart
  lib/domain/param/store/get_store_summary_params.dart
  lib/domain/param/store/get_stores_by_location_params.dart
  lib/domain/repository/store_repository.dart
  lib/domain/usecase/store/get_my_preferences_stores_by_location_usecase.dart
  lib/domain/usecase/store/get_store_summary_usecase.dart
  lib/domain/usecase/store/get_stores_by_location_usecase.dart
  lib/presentation/local_login/generated/local_login_view_model.freezed.dart
  lib/presentation/map/extension/map_method_extensions.dart
  lib/presentation/map/extension/map_view_extensions.dart
  lib/presentation/map/generated/map_view_model.freezed.dart
  lib/presentation/map/map_state.dart
  lib/presentation/map/map_view.dart
  lib/presentation/map/map_view_model.dart
  lib/presentation/router/router.dart
Labels: enhancement

#43 [FEATURE] 지도 > 검색 페이지 기능 구현
  asset/icon/arrow/20x20_arrow_down_filled.svg
  asset/icon/arrow/20x20_arrow_up_filled.svg
  lib/common/design_system/component/top_bar/main_top_bar.dart
  lib/common/design_system/component/top_bar/resource/top_bar_icon.dart
  lib/common/design_system/component/top_bar/sub_top_bar.dart
  lib/common/gen_asset/assets.gen.dart
  lib/data/data_source/mock/search_mock_data_source.dart
  lib/data/data_source/remote/search_remote_data_source.dart
  lib/data/entity/search/generated/search_popular_entity.g.dart
  lib/data/entity/search/search_popular_entity.dart
  lib/data/mapper/search_mapper.dart
  lib/data/query_param/store/generated/get_stores_by_location_query_param.g.dart
  lib/data/query_param/store/get_stores_by_location_query_param.dart
  lib/data/repository_impl/search_repository_impl.dart
  lib/domain/model/search/popular_searchs_model.dart
  lib/domain/model/search/recent_search_model.dart
  lib/domain/param/search/delete_recent_search_params.dart
  lib/domain/param/search/get_popular_searches_params.dart
  lib/domain/repository/search_repository.dart
  lib/domain/usecase/search/delete_recent_search_all_usecase.dart
  lib/domain/usecase/search/delete_recent_search_usecase.dart
  lib/domain/usecase/search/get_popular_searches_usecase.dart
  lib/domain/usecase/search/get_recent_searches_usecase.dart
  lib/presentation/map/extension/map_view_extensions.dart
  lib/presentation/map/generated/map_view_model.freezed.dart
  lib/presentation/map/map_state.dart
  lib/presentation/map/map_view.dart
  lib/presentation/map/map_view_model.dart
  lib/presentation/map/search/generated/search_store_view_model.freezed.dart
  lib/presentation/map/search/search_store_state.dart
  lib/presentation/map/search/search_store_view.dart
  lib/presentation/map/search/search_store_view_model.dart
  lib/presentation/router/router.dart
  lib/presentation/router/routes.dart
Labels: enhancement

#45 [FEATURE] 가게 상세 조회 기능 구현 (PART 1)
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/common/design_system/component/etc/map/store_info_bottom_sheet_content.dart
  lib/core/resource/api_call.dart
  lib/core/resource/constant.dart
  lib/core/util/naver_map_util.dart
  lib/data/data_source/mock/store_mock_data_source.dart
  lib/data/data_source/remote/generated/store_notice_remote_data_source.g.dart
  lib/data/data_source/remote/store_notice_remote_data_source.dart
  lib/data/entity/store/generated/store_detail_entity.g.dart
  lib/data/entity/store/store_detail_entity.dart
  lib/data/entity/store_notice/generated/store_notice_entity.g.dart
  lib/data/entity/store_notice/store_notice_entity.dart
  lib/data/mapper/store_mapper.dart
  lib/data/mapper/store_notice_mapper.dart
  lib/data/repository_impl/store_notice_repository_impl.dart
  lib/data/repository_impl/store_repository_impl.dart
  lib/domain/model/store/store_detail_model.dart
  lib/domain/model/store/store_operating_hour_model.dart
  lib/domain/model/store_notice/store_notice_model.dart
  lib/domain/param/store/get_store_detail_params.dart
  lib/domain/param/store_notice/get_store_notices_params.dart
  lib/domain/repository/store_notice_repository.dart
  lib/domain/repository/store_repository.dart
  lib/domain/usecase/store/get_store_detail_usecase.dart
  lib/domain/usecase/store_notice/get_store_notices_usecase.dart
  lib/presentation/map/extension/map_view_extensions.dart
  lib/presentation/map/map_view.dart
  lib/presentation/map/store_detail/find_place_by_map_view.dart
  lib/presentation/map/store_detail/generated/store_detail_view_model.freezed.dart
  lib/presentation/map/store_detail/local_widget/introduce.dart
  lib/presentation/map/store_detail/local_widget/notice.dart
  lib/presentation/map/store_detail/local_widget/owner_pick_image.dart
  lib/presentation/map/store_detail/local_widget/store_detail_info.dart
  lib/presentation/map/store_detail/local_widget/store_representive_info.dart
  lib/presentation/map/store_detail/store_detail_state.dart
  lib/presentation/map/store_detail/store_detail_view.dart
  lib/presentation/map/store_detail/store_detail_view_model.dart
  lib/presentation/router/router.dart
  lib/presentation/router/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#46 [FEATURE] 사용자 쿠폰 관련 API 연동 및 로직 추가
  lib/core/resource/constant.dart
  lib/data/data_source/remote/generated/user_coupon_remote_data_source.g.dart
  lib/data/data_source/remote/user_coupon_remote_data_source.dart
  lib/data/entity/user_coupon/coupon_detail_entity.dart
  lib/data/entity/user_coupon/coupon_entity.dart
  lib/data/entity/user_coupon/coupon_usage_status_entity.dart
  lib/data/entity/user_coupon/generated/coupon_detail_entity.g.dart
  lib/data/entity/user_coupon/generated/coupon_entity.g.dart
  lib/data/entity/user_coupon/generated/coupon_usage_status_entity.g.dart
  lib/data/mapper/user_coupon_mapper.dart
  lib/data/repository_impl/user_coupon_repository_impl.dart
  lib/data/request_body/user_coupon/generated/issue_coupon_request_body.g.dart
  lib/data/request_body/user_coupon/issue_coupon_request_body.dart
  lib/domain/model/user_coupon/coupon_detail_model.dart
  lib/domain/model/user_coupon/coupon_model.dart
  lib/domain/model/user_coupon/coupon_usage_status_model.dart
  lib/domain/param/user_coupon/get_my_coupon_detail_params.dart
  lib/domain/param/user_coupon/issue_coupon_params.dart
  lib/domain/repository/user_coupon_repository.dart
  lib/domain/usecase/user_coupon/get_coupon_usage_status_usecase.dart
  lib/domain/usecase/user_coupon/get_my_coupon_detail_usecase.dart
  lib/domain/usecase/user_coupon/get_my_coupons_usecase.dart
  lib/domain/usecase/user_coupon/issue_coupon_usecase.dart
Labels: enhancement

#49 [FEATURE] 내 취향 선택
  asset/icon/etc/hexagon_11.svg
  asset/icon/etc/hexagon_12.svg
  asset/icon/etc/hexagon_13.svg
  asset/image/1.5x/logo_bee.png
  asset/image/1.5x/logo_bee_inversion.png
  asset/image/2.0x/logo_bee.png
  asset/image/2.0x/logo_bee_inversion.png
  asset/image/3.0x/logo_bee.png
  asset/image/3.0x/logo_bee_inversion.png
  asset/image/4.0x/logo_bee.png
  asset/image/4.0x/logo_bee_inversion.png
  asset/image/logo_bee.png
  asset/image/logo_bee_inversion.png
  lib/common/design_system/component/button/pill_button.dart
  lib/common/design_system/component/button/text_button.dart
  lib/common/gen_asset/assets.gen.dart
  lib/core/resource/generated/token_info.g.dart
  lib/core/resource/network/app_dio.dart
  lib/core/resource/secure_storage/secure_storage.dart
  lib/core/resource/token_info.dart
  lib/data/entity/auth/local_login_entity.dart
  lib/domain/repository/preference_repository.dart
  lib/presentation/global/preference/generated/preference_view_model.freezed.dart
  lib/presentation/global/preference/preference_state.dart
  lib/presentation/global/preference/preference_view_model.dart
  lib/presentation/local_login/local_login_view.dart
  lib/presentation/local_login/local_login_view_model.dart
  lib/presentation/router/router.dart
  lib/presentation/router/routes.dart
  lib/presentation/taste/my_taste_choice/generated/my_taste_choice_view_model.freezed.dart
  lib/presentation/taste/my_taste_choice/my_taste_choice_state.dart
  lib/presentation/taste/my_taste_choice/my_taste_choice_view_model.dart
  lib/presentation/taste/my_taste_choice/view/my_taste_choice_start.dart
  lib/presentation/taste/my_taste_choice/view/my_taste_choice_step1.dart
  lib/presentation/taste/my_taste_choice/view/my_taste_choice_step2.dart
  lib/presentation/taste/my_taste_choice/view/my_taste_choice_step3.dart
  lib/presentation/taste/my_taste_choice/view/my_taste_choice_step4.dart
  lib/presentation/taste/my_taste_choice/widget/my_taste_wrapper.dart
  lib/presentation/taste/result/view/result.dart
  lib/presentation/taste/result/view/result_loading.dart
  lib/presentation/taste/util/taste_skip_bottom_sheet.dart
Labels: enhancement

#47 [FEATURE] 가게 상세 조회 기능 구현 (PART 2)
  lib/common/design_system/component/badge/number_badge.dart
  lib/data/data_source/mock/store_notice_mock_data_source.dart
  lib/data/data_source/remote/coupon_remote_data_source.dart
  lib/data/data_source/remote/generated/coupon_remote_data_source.g.dart
  lib/data/data_source/remote/generated/user_coupon_remote_data_source.g.dart
  lib/data/data_source/remote/store_notice_remote_data_source.dart
  lib/data/data_source/remote/user_coupon_remote_data_source.dart
  lib/data/entity/coupon/coupon_entity.dart
  lib/data/entity/coupon/generated/coupon_entity.g.dart
  lib/data/entity/store/generated/store_detail_entity.g.dart
  lib/data/entity/store/store_detail_entity.dart
  lib/data/entity/user_coupon/coupon_detail_entity.dart
  lib/data/entity/user_coupon/coupon_entity.dart
  lib/data/entity/user_coupon/coupon_issue_status_entity.dart
  lib/data/entity/user_coupon/coupon_usage_status_entity.dart
  lib/data/entity/user_coupon/generated/coupon_detail_entity.g.dart
  lib/data/entity/user_coupon/generated/coupon_entity.g.dart
  lib/data/entity/user_coupon/generated/coupon_issue_status_entity.g.dart
  lib/data/entity/user_coupon/generated/coupon_usage_status_entity.g.dart
  lib/data/mapper/coupon_mapper.dart
  lib/data/mapper/store_mapper.dart
  lib/data/mapper/user_coupon_mapper.dart
  lib/data/repository_impl/coupon_repository_impl.dart
  lib/data/repository_impl/user_coupon_repository_impl.dart
  lib/domain/model/coupon/coupon_model.dart
  lib/domain/model/store/store_detail_model.dart
  lib/domain/model/user_coupon/coupon_detail_model.dart
  lib/domain/model/user_coupon/coupon_issue_status_model.dart
  lib/domain/model/user_coupon/coupon_model.dart
  lib/domain/model/user_coupon/coupon_usage_status_model.dart
  lib/domain/param/coupon/get_coupons_by_store_params.dart
  lib/domain/param/user_coupon/get_coupon_issue_status_params.dart
  lib/domain/repository/coupon_repository.dart
  lib/domain/repository/user_coupon_repository.dart
  lib/domain/usecase/coupon/get_coupons_by_store_usecase.dart
  lib/domain/usecase/user_coupon/get_coupon_issue_status_usecase.dart
  lib/domain/usecase/user_coupon/get_coupon_usage_status_usecase.dart
  lib/domain/usecase/user_coupon/get_my_coupon_detail_usecase.dart
  lib/domain/usecase/user_coupon/get_my_coupons_usecase.dart
  lib/presentation/map/extension/map_method_extensions.dart
  lib/presentation/map/store_detail/local_widget/dessert_images.dart
  lib/presentation/map/store_detail/local_widget/failure.dart
  lib/presentation/map/store_detail/local_widget/introduce.dart
  lib/presentation/map/store_detail/local_widget/menus.dart
  lib/presentation/map/store_detail/local_widget/notice.dart
  lib/presentation/map/store_detail/local_widget/tab_bar.dart
  lib/presentation/map/store_detail/notice/generated/store_notice_view_model.freezed.dart
  lib/presentation/map/store_detail/notice/local_widget/failure.dart
  lib/presentation/map/store_detail/notice/local_widget/notice.dart
  lib/presentation/map/store_detail/notice/store_notice_detail_view.dart
  lib/presentation/map/store_detail/notice/store_notice_state.dart
  lib/presentation/map/store_detail/notice/store_notice_view.dart
  lib/presentation/map/store_detail/notice/store_notice_view_model.dart
  lib/presentation/map/store_detail/store_detail_view.dart
  lib/presentation/router/router.dart
  lib/presentation/router/routes.dart
  lib/presentation/widget/coupon_card.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#50 [FEATURE] 디저트메이트 메인 화면
  asset/icon/etc/bookmark_selected.svg
  asset/icon/etc/bookmark_unselected.svg
  asset/icon/file/no_image_status.svg
  ios/Podfile.lock
  lib/common/design_system/component/button/floating_action_button.dart
  lib/common/design_system/component/chip/custom_chip.dart
  lib/common/design_system/component/chip/suggestive_chip.dart
  lib/common/design_system/component/profile_photo/profile_photo_edit.dart
  lib/common/design_system/component/profile_photo/profile_photo_setting.dart
  lib/common/design_system/component/profile_photo/profile_photo_size.dart
  lib/common/design_system/component/tag/label_tag.dart
  lib/common/design_system/component/top_bar/resource/top_bar_icon.dart
  lib/common/design_system/foundation/shadow/shadow_config.dart
  lib/common/gen_asset/assets.gen.dart
  lib/core/resource/constant.dart
  lib/core/resource/extension.dart
  lib/data/data_source/remote/generated/mate_remote_data_source.g.dart
  lib/data/data_source/remote/mate_remote_data_source.dart
  lib/data/entity/mate/generated/mate_detail_entity.g.dart
  lib/data/entity/mate/generated/mate_entity.g.dart
  lib/data/entity/mate/mate_detail_entity.dart
  lib/data/entity/mate/mate_entity.dart
  lib/data/mapper/mate_mapper.dart
  lib/data/query_param/mate/generated/get_mate_query_param.g.dart
  lib/data/query_param/mate/get_mate_query_param.dart
  lib/data/repository_impl/mate_repository_impl.dart
  lib/domain/model/mate/mate_detail_model.dart
  lib/domain/model/mate/mate_model.dart
  lib/domain/param/mate/get_mate_params.dart
  lib/domain/repository/mate_repository.dart
  lib/domain/usecase/mate/get_mate_usecase.dart
  lib/presentation/dessert/dessert_board_state.dart
  lib/presentation/dessert/dessert_board_view.dart
  lib/presentation/dessert/dessert_board_view_model.dart
  lib/presentation/dessert/generated/dessert_board_view_model.freezed.dart
  lib/presentation/dessert/widget/list/dessert_list_body.dart
  lib/presentation/dessert/widget/list/dessert_list_card.dart
  lib/presentation/dessert/widget/list/dessert_list_footer.dart
  lib/presentation/dessert/widget/list/dessert_list_header.dart
  lib/presentation/dessert/widget/list/dessert_list_image.dart
  lib/presentation/router/router.dart
  lib/presentation/router/routes.dart
Labels: enhancement

#52 [FEATURE] 자잘한 수정
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/common/design_system/component/etc/map/store_info_bottom_sheet_content.dart
  lib/common/design_system/component/top_bar/main_top_bar.dart
  lib/common/design_system/component/top_bar/resource/top_bar_icon.dart
  lib/common/gen_asset/assets.gen.dart
  lib/data/data_source/mock/auth_mock_data_source.dart
  lib/presentation/dessert/dessert_board_view.dart
  lib/presentation/local_login/local_login_view.dart
  lib/presentation/map/map_view.dart
  lib/presentation/map/search/local_widget/search_bar.dart
  lib/presentation/map/search/local_widget/search_keyword_list.dart
  lib/presentation/map/search/search_store_view_model.dart
  lib/presentation/map/store_detail/local_widget/tab_bar.dart
  lib/presentation/map/store_detail/store_detail_view.dart
  lib/presentation/map/user_store/add/add_user_store_list_view.dart
  lib/presentation/router/router.dart
Labels: enhancement

#53 [SETUP] 연결
  asset/image/1.5x/splash.png
  asset/image/2.0x/splash.png
  asset/image/3.0x/splash.png
  asset/image/4.0x/splash.png
  asset/image/splash.png
  ios/Podfile.lock
  lib/common/gen_asset/assets.gen.dart
  lib/core/resource/network/app_dio.dart
  lib/presentation/local_login/local_login_view.dart
  lib/presentation/router/router.dart
  lib/presentation/sign_up/sign_up_view_model.dart
  lib/presentation/sign_up/view/sign_up_step5.dart
  lib/presentation/splash_view.dart
  lib/presentation/taste/my_taste_choice/view/my_taste_choice_start.dart
  lib/presentation/taste/result/view/result.dart
  lib/presentation/taste/util/taste_skip_bottom_sheet.dart
Labels: enhancement

#54 [FEATURE] Global Bottom Navigation
  lib/common/design_system/component/navigation_bar/navigation_bar.dart
  lib/presentation/dessert/dessert_board_view.dart
  lib/presentation/router/router.dart
  lib/presentation/widget/desserbee_bottom_navigation.dart
Labels: enhancement

#55 [FEATURE] 저장 리스트에 가게 추가 기능 구현
  android/app/src/main/kotlin/com/desserbee/frontendMobile/MainActivity.kt
  ios/Podfile.lock
  ios/Runner/Runner.entitlements
  lib/core/resource/network/app_dio.dart
  lib/data/repository_impl/user_store_repository_impl.dart
  lib/domain/param/user_store/add_store_to_user_store_list_params.dart
  lib/domain/repository/user_store_repository.dart
  lib/domain/usecase/user_store/add_store_to_user_store_list_usecase.dart
  lib/presentation/map/map_view.dart
  lib/presentation/map/store_detail/store_detail_view.dart
  lib/presentation/map/store_detail/user_store/add_store_to_user_store_list_state.dart
  lib/presentation/map/store_detail/user_store/add_store_to_user_store_list_view.dart
  lib/presentation/map/store_detail/user_store/add_store_to_user_store_list_view_model.dart
  lib/presentation/map/store_detail/user_store/generated/add_store_to_user_store_list_view_model.freezed.dart
  lib/presentation/router/router.dart
  lib/presentation/router/routes.dart
Labels: enhancement

#56 [FIX] 이미지 4개 추가 & 내 취향 선택
  asset/image/1.5x/flower_bee_1.png
  asset/image/1.5x/honey_pot_1.png
  asset/image/1.5x/register-bee.png
  asset/image/1.5x/rest_bee_1.png
  asset/image/2.0x/flower_bee_1.png
  asset/image/2.0x/honey_pot_1.png
  asset/image/2.0x/register-bee.png
  asset/image/2.0x/rest_bee_1.png
  asset/image/3.0x/flower_bee_1.png
  asset/image/3.0x/honey_pot_1.png
  asset/image/3.0x/register-bee.png
  asset/image/3.0x/rest_bee_1.png
  asset/image/4.0x/flower_bee_1.png
  asset/image/4.0x/honey_pot_1.png
  asset/image/4.0x/register-bee.png
  asset/image/4.0x/rest_bee_1.png
  asset/image/flower_bee_1.png
  asset/image/honey_pot_1.png
  asset/image/register-bee.png
  asset/image/rest_bee_1.png
  lib/common/gen_asset/assets.gen.dart
  lib/core/resource/api_call.dart
  lib/core/resource/exception/custom_exception.dart
  lib/core/resource/exception/generated/custom_exception.freezed.dart
  lib/presentation/router/router.dart
  lib/presentation/sign_up/view/sign_up_step6.dart
  lib/presentation/taste/my_taste_choice/view/my_taste_choice_start.dart
  lib/presentation/taste/result/view/result.dart
  lib/presentation/taste/util/taste_skip_bottom_sheet.dart
Labels: bug

#57 [SETUP] IOS 배포 관련 설정
  android/app/build.gradle.kts
  android/app/src/main/kotlin/com/dessert/desserbee/MainActivity.kt
  ios/Runner.xcodeproj/project.pbxproj
  lib/presentation/widget/wrapper.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#59 [FEATURE] 마이페이지 구현
  lib/common/design_system/component/profile_photo/profile_photo_edit.dart
  lib/common/design_system/component/profile_photo/profile_photo_setting.dart
  lib/common/design_system/component/profile_photo/profile_photo_size.dart
  lib/core/util/image_util.dart
  lib/data/data_source/mock/user_mock_data_source.dart
  lib/data/data_source/remote/generated/user_remote_data_source.g.dart
  lib/data/data_source/remote/store_remote_data_source.dart
  lib/data/data_source/remote/user_remote_data_source.dart
  lib/data/repository_impl/store_repository_impl.dart
  lib/data/repository_impl/user_repository_impl.dart
  lib/data/request_body/user/generated/patch_me_request_body.g.dart
  lib/data/request_body/user/patch_me_request_body.dart
  lib/domain/param/user/update_profile_image_params.dart
  lib/domain/repository/user_repository.dart
  lib/domain/usecase/user/delete_me_usecase.dart
  lib/domain/usecase/user/update_profile_image_usecase.dart
  lib/presentation/map/local_widget/store_list_sheet.dart
  lib/presentation/map/search/local_widget/failure.dart
  lib/presentation/map/search/search_store_view.dart
  lib/presentation/my_page/my_page_view.dart
  lib/presentation/my_page/policy/my_policy_view.dart
  lib/presentation/my_page/setting/delete_my_info/delete_my_info_state.dart
  lib/presentation/my_page/setting/delete_my_info/delete_my_info_view.dart
  lib/presentation/my_page/setting/delete_my_info/delete_my_info_view_model.dart
  lib/presentation/my_page/setting/delete_my_info/generated/delete_my_info_view_model.freezed.dart
  lib/presentation/my_page/setting/my_setting_view.dart
  lib/presentation/my_page/update_profile/generated/update_profile_info_view_model.freezed.dart
  lib/presentation/my_page/update_profile/local_widget/preferences.dart
  lib/presentation/my_page/update_profile/local_widget/profile_image_and_nickname.dart
  lib/presentation/my_page/update_profile/local_widget/save_button.dart
  lib/presentation/my_page/update_profile/update_profile_info_state.dart
  lib/presentation/my_page/update_profile/update_profile_info_view.dart
  lib/presentation/my_page/update_profile/update_profile_info_view_model.dart
  lib/presentation/my_page/user_store/generated/my_user_store_list_view_model.freezed.dart
  lib/presentation/my_page/user_store/my_user_store_list_state.dart
  lib/presentation/my_page/user_store/my_user_store_list_view.dart
  lib/presentation/my_page/user_store/my_user_store_list_view_model.dart
  lib/presentation/router/router.dart
  lib/presentation/router/routes.dart
  lib/presentation/widget/default_error.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#61 [FEATURE] 한줄 리뷰 조회 구현
  asset/icon/etc/16_star_filled.svg
  ios/Podfile.lock
  lib/common/gen_asset/assets.gen.dart
  lib/data/data_source/remote/generated/store_review_remote_data_source.g.dart
  lib/data/data_source/remote/store_review_remote_data_source.dart
  lib/data/repository_impl/store_review_repository_impl.dart
  lib/domain/param/store_review/add_store_review_params.dart
  lib/domain/param/store_review/delete_store_review_params.dart
  lib/domain/param/store_review/update_store_review_params.dart
  lib/domain/repository/store_review_repository.dart
  lib/domain/usecase/store_review/add_store_review_usecase.dart
  lib/domain/usecase/store_review/delete_store_review_usecase.dart
  lib/domain/usecase/store_review/update_store_review_usecase.dart
  lib/presentation/map/store_detail/local_widget/dessert_images.dart
  lib/presentation/map/store_detail/local_widget/menus.dart
  lib/presentation/map/store_detail/local_widget/store_reviews.dart
  lib/presentation/map/store_detail/local_widget/tab_bar.dart
  lib/presentation/map/store_detail/store_detail_view.dart
  lib/presentation/my_page/my_page_view.dart
  lib/presentation/widget/store_review_card.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#60 [BUGFIX] 최근 검색어 클릭 시 검색어가 삭제되는 버그 수정
  ios/Podfile.lock
  lib/presentation/map/search/local_widget/search_keyword_list.dart
  lib/presentation/map/search/search_store_view.dart
Labels: bug, enhancement

#66 [FEATURE] 내가 참여한 디저트 메이트 조회
  asset/icon/etc/friends.svg
  asset/icon/etc/review.svg
  lib/common/design_system/component/etc/map/store_info_bottom_sheet_content.dart
  lib/common/gen_asset/assets.gen.dart
  lib/data/data_source/remote/generated/mate_remote_data_source.g.dart
  lib/data/data_source/remote/mate_remote_data_source.dart
  lib/data/mapper/mate_mapper.dart
  lib/data/query_param/mate/generated/get_my_mate_query_param.g.dart
  lib/data/query_param/mate/get_my_mate_query_param.dart
  lib/data/repository_impl/mate_repository_impl.dart
  lib/domain/param/mate/get_my_mate_params.dart
  lib/domain/repository/mate_repository.dart
  lib/domain/usecase/mate/get_my_mate_usecase.dart
  lib/presentation/dessert/dessert_board_view.dart
  lib/presentation/map/extension/map_method_extensions.dart
  lib/presentation/map/extension/map_view_extensions.dart
  lib/presentation/map/generated/map_view_model.freezed.dart
  lib/presentation/map/map_state.dart
  lib/presentation/map/map_view.dart
  lib/presentation/map/map_view_model.dart
  lib/presentation/map/store_detail/local_widget/failure.dart
  lib/presentation/my_page/dessert_mate/generated/my_dessert_mate_view_model.freezed.dart
  lib/presentation/my_page/dessert_mate/local_widget/approved_mate.dart
  lib/presentation/my_page/dessert_mate/local_widget/my_mate.dart
  lib/presentation/my_page/dessert_mate/local_widget/saved_mate.dart
  lib/presentation/my_page/dessert_mate/local_widget/tab_bar.dart
  lib/presentation/my_page/dessert_mate/my_dessert_mate_state.dart
  lib/presentation/my_page/dessert_mate/my_dessert_mate_view.dart
  lib/presentation/my_page/dessert_mate/my_dessert_mate_view_model.dart
  lib/presentation/my_page/local_widget/customer_support.dart
  lib/presentation/my_page/local_widget/my_activity.dart
  lib/presentation/my_page/local_widget/profile_info.dart
  lib/presentation/my_page/my_page_view.dart
  lib/presentation/router/router.dart
  lib/presentation/router/routes.dart
Labels: enhancement
